# const
DELIMITER = ','

COL_INDEX = 'index'
PICTURE_NAME = 'file name'
R_X = 'rx'
R_Y = 'ry'
R_Z = 'rz'
T_X = 'tx'
T_Y = 'ty'
T_Z = 'tz'
THETA = 'theta'

CSV_VALUES_LABELS = [R_X, R_Y, R_Z, T_X, T_Y, T_Z]
VALIDATION_CSV_VALUES_LABELS = [R_X, R_Y, R_Z]
FINAL_OUTPUT_CSV_VALUES_LABELS = [PICTURE_NAME, R_X, R_Y, R_Z]
FINAL_OUTPUT_CSV_VALUES_LABELS_THETA = [PICTURE_NAME, R_X, R_Y, R_Z, THETA]

CSV_LABELS = [COL_INDEX, PICTURE_NAME, R_X, R_Y, R_Z, T_X, T_Y, T_Z]

CSV_LABELS_DIFF = [COL_INDEX, PICTURE_NAME, R_X, R_Y, R_Z, T_X, T_Y, T_Z, THETA]
