DEFAULT_RANDOM_STATE = 0
DEFAULT_TRAIN_RATE = 0.7

DEFAULT_TEST_RATE = 0.3
DEFAULT_VALID_RATE = 0.1

LANDMARKS_SHAPE = (68, 2)
PICTURE_SIZE = 100
BATCH_SIZE = 64
OUT_DIM = 6

CANNY_SIGMA = 1 / 3

LANDMARKS_PREFIX = '_landmarks_'

LANDMARKS_FILE_SUFFIX = '.pts'

PICTURE_SUFFIX = ['jpg', 'png']
