DEFAULT_RANDOM_STATE = 0
DEFAULT_TRAIN_RATE = 0.7

DEFAULT_TEST_RATE = 0.02
DEFAULT_VALID_RATE = 0.5

LANDMARKS_SHAPE = (68, 2)
PICTURE_SIZE = 200
OUT_DIM = 3
DEFAULT_ROI_FACTOR = 0.2
OFFSET_ROI = 0.05

CANNY_SIGMA = 1 / 3

LANDMARKS_PREFIX = '_landmarks_'

LANDMARKS_FILE_SUFFIX = '.pts'

PICTURE_SUFFIX = ['jpg', 'png']
