MY_MODEL_LOCAL_PATH = "../model_values/"

# stats file consts
MODEL_STATES_FILE = "states.npy"
MODEL_STATES_FILE_PATH = MY_MODEL_LOCAL_PATH + '/' + MODEL_STATES_FILE

# OPTIONS = [M]
MY_MODEL_NAME = 'KerasModel.h5'
MY_MODEL_PICKLE = 'KerasModel.pkl'

MODEL_NAME_PATH = MY_MODEL_LOCAL_PATH + MY_MODEL_NAME

BATCH_SIZE = 32
EPOCHS = 120
